### ISSUE TITLE
ERROR INSTALLING: "iconv could not be found in item_rev/languages/iconv"

### ISSUE THREAD

**Issue by neuroghast** [BartyMae/IR_Revised#20]
Hi there.

Was trying to install this at the end-ish of my modlist when I got this error right off the bat:

```
ERROR: Failure("ERROR: charsets were not converted because iconv could not be found in item_rev/languages/iconv")
Please submit a report regarding this problem, including the information contained in SETUP-ITEM_REV.DEBUG and look for support at: Bartimaeus in the IR Revised thread at forums.gibberlings3.net
Using Language [English]
[English] has 1 top-level TRA files
[item_rev/languages/english/setup.tra] has 61 translation strings
```
This happened when installing the mod both on BG1 and BG2 main folders, separately.

I searched a bit before opening this issue and found [this post](https://www.gibberlings3.net/forums/topic/28894-ir-revised-v13800-2022-january-11th/page/106/#findComment-326115) on the G3 official thread. I've tried deleting all the mod's files and folder, as you suggested, with no luck on the next try

Some additional info that might be useful:

- I've installed it as recommended: extracted the original IR, then extracted and overwrite every IR folder and file with IR_revised stuff. I even tried to extract IR on my desktop (instead of directly on the games folder), but the same thing happened;
- I've installed this mod previously on **BG1** without any issue. I uninstalled it simply because of order, as someone recommended spells tweaks > class and kit tweaks > items tweaks. Don't remember having any major problem installing or uninstalling it before;
- On BG2, however, it wasn't installed at any time, as I was stuck for weeks trying (and failing) to solve an issue with crossmod banter pack;
- Not sure if this info has any use to this specific problem, but I plan to change my items sections with this mod, SubtleDoctor's Items Tweaks and Forgotten Armament by Morpheus, in this order.

Note I only attached one debug file (and changed it's extension to .txt so I could paste it here) for convenience, since I imagine it will be basically the same, as the error occurred right at the start.

Please let me know if I can provide any more info and thanks in advance!

[WeiDU_bg1.log](https://github.com/user-attachments/files/18254754/WeiDU_bg1.log)
[WeiDU_bg2.log](https://github.com/user-attachments/files/18254757/WeiDU_bg2.log)
[SETUP-ITEM_REV.txt](https://github.com/user-attachments/files/18254759/SETUP-ITEM_REV.txt)

QUICK EDIT: I forgot to test IR without IR_Revised overwriting it. It turns out it skips ALL components, saying it's not compatible with the game. Happens on BG1 and 2, as you can see here:

![ir_rev](https://github.com/user-attachments/assets/6cc0a2a0-dac4-43f4-8513-7855c41290d7)

**Comment by BartyMae** [comment]
Hello @neuroghast! Your error is saying that iconv cannot be found, which is an application supplied with the official version of IR but not IRR (as IRR does not modify this part of the installation - it assumes it will be there when you combine IRR's "item_rev" folder into IR's "item_rev" folder). In your game directory, can you navigate to "item_rev\languages\iconv" and see if iconv.exe is there (or if the iconv folder exists at all)? If it's not there, your folders have not been combined correctly - it's likely your operating system is setup to overwrite instead of combine folders, which will lead to a number of files that are supposed to be used in the IRR installation being deleted when they should not be. I can supply a correctly combined folder if that is indeed the case.

**Comment by neuroghast** [comment]
Hi! Thanks for the reply!

So, the folder is not there, but I don't think it's windows fault. If it was, it would've created this same issue with SR_Revised, no? And that went just fine.

To top that off, I've checked, re-checked and re-downloaded IR a few times (from G3, from their GitHub, the exe and the source code version). And in all cases, the languages is missing the iconv folder. They look like this in all cases:
![image](https://github.com/user-attachments/assets/70ba3ba4-432b-4130-93e5-9295004f144e)

I've also typed "iconv" on my BGs main folder and found a few mods that have it. Can I simply copy paste it on the languages folder to solve this issue? Just trying to solve this without bothering you anymore, as it seems it's not even a problem with IR_Revised, but the absence of these folders and files from the original IR.

Thanks again and sorry for the misunderstanding!

QUICK EDIT: downloaded one more time from their GH and now I've the correct folder. I honestly can't tell you HOW this happened, but at least I think it's possible to install now!

**Comment by BartyMae** [comment]
I suspect that this is most likely an issue of you downloading Item Revisions V3 instead of V4. If you've downloaded the "latest release" at the G3, you will have downloaded the ancient V3 version, which is close to ten years out of date. Try downloading V4 B10, the latest V4 release, on GitHub here: https://github.com/Gibberlings3/ItemRevisions/releases

And I just refreshed the page and I see that you've made an edit where you discovered the issue. It probably wasn't _really_ your fault, the official G3 page should have the V4 version (and should've for many years at this point, but I guess that's the nature of permanent betas).

**Comment by neuroghast** [comment]
Yeah, good call. I'm not used to use GH on a daily basis and thought the right way was to always download the latest releases, as the name implies lol I just hope this was a one-off case; I downloaded A LOT of things from Gibberlings3

Anyway, thanks again for taking your time. Helpful as always! Have a great new year!
